// All English educational content pools - randomized per session.

export interface QuizQ {
  q: string;
  options: string[];
  answer: number; // index
}

export const GRAMMAR_TOPICS: string[] = [
  "Present Simple",
  "Present Continuous",
  "Present Perfect",
  "Present Perfect Continuous",
  "Past Simple",
  "Past Continuous",
  "Past Perfect",
  "Past Perfect Continuous",
  "Future Simple (will)",
  "Future with (be going to)",
  "Future Continuous",
  "Future Perfect",
  "Articles (a/an/the)",
  "Nouns & Plurals",
  "Pronouns",
  "Adjectives & Adverbs",
  "Comparatives & Superlatives",
  "Modal Verbs",
  "Conditionals",
  "Passive Voice",
  "Reported Speech",
  "Prepositions",
  "Conjunctions",
  "Question Forms",
  "Phrasal Verbs",
  "Gerunds & Infinitives",
];

export const YOUTUBE_PLACEHOLDER = "https://www.youtube.com/embed/vE-z2dNMbHA";

// LEVEL-BASED EXERCISES
// Level 1: Beginner (A1) - 25 questions
export const LEVEL_1_QUESTIONS: QuizQ[] = [
  { q: "I ___ a student.", options: ["am", "is", "are", "be"], answer: 0 },
  { q: "She ___ from Mongolia.", options: ["am", "is", "are", "be"], answer: 1 },
  { q: "They ___ playing now.", options: ["is", "am", "are", "be"], answer: 2 },
  { q: "What is your name?", options: ["I name John", "My name John", "I'm John", "Name is John"], answer: 2 },
  { q: "He ___ to school every day.", options: ["go", "goes", "going", "gone"], answer: 1 },
  { q: "I ___ a dog.", options: ["have", "has", "having", "had"], answer: 0 },
  { q: "She ___ coffee.", options: ["drink", "drinks", "drinking", "drank"], answer: 1 },
  { q: "They ___ from China.", options: ["is", "are", "am", "be"], answer: 1 },
  { q: "I ___ English.", options: ["speak", "speaks", "speaking", "spoke"], answer: 0 },
  { q: "It ___ sunny today.", options: ["is", "am", "are", "be"], answer: 0 },
  { q: "You ___ a teacher.", options: ["is", "are", "am", "be"], answer: 1 },
  { q: "We ___ friends.", options: ["is", "am", "are", "be"], answer: 2 },
  { q: "This ___ a book.", options: ["is", "am", "are", "be"], answer: 0 },
  { q: "She ___ three children.", options: ["have", "has", "having", "had"], answer: 1 },
  { q: "I ___ in a house.", options: ["live", "lives", "living", "lived"], answer: 0 },
  { q: "He ___ football.", options: ["play", "plays", "playing", "played"], answer: 1 },
  { q: "They ___ happy.", options: ["is", "are", "am", "be"], answer: 1 },
  { q: "Where ___ you from?", options: ["are", "is", "am", "be"], answer: 0 },
  { q: "What ___ your phone number?", options: ["are", "is", "am", "be"], answer: 1 },
  { q: "I ___ rice every day.", options: ["eat", "eats", "eating", "ate"], answer: 0 },
  { q: "She ___ at the hospital.", options: ["work", "works", "working", "worked"], answer: 1 },
  { q: "My sister ___ a singer.", options: ["is", "am", "are", "be"], answer: 0 },
  { q: "The weather ___ nice.", options: ["is", "am", "are", "be"], answer: 0 },
  { q: "I ___ not a doctor.", options: ["am", "is", "are", "be"], answer: 0 },
  { q: "They ___ students.", options: ["is", "are", "am", "be"], answer: 1 },
];

// Level 2: Elementary (A2) - 25 questions
export const LEVEL_2_QUESTIONS: QuizQ[] = [
  { q: "Listen! The baby ___.", options: ["cries", "is crying", "cry", "cried"], answer: 1 },
  { q: "She ___ her homework right now.", options: ["do", "does", "is doing", "did"], answer: 2 },
  { q: "I ___ to school yesterday.", options: ["go", "goes", "went", "going"], answer: 2 },
  { q: "He ___ tennis last week.", options: ["play", "plays", "played", "playing"], answer: 2 },
  { q: "They ___ for the bus when it ___.", options: ["wait/comes", "are waiting/comes", "waited/came", "waiting/coming"], answer: 1 },
  { q: "___ apple a day keeps the doctor away.", options: ["A", "An", "The", "-"], answer: 0 },
  { q: "Water ___ at 100°C.", options: ["boil", "boils", "boiling", "boiled"], answer: 1 },
  { q: "She ___ to the market yesterday.", options: ["go", "goes", "went", "going"], answer: 2 },
  { q: "There ___ many books on the shelf.", options: ["is", "are", "was", "be"], answer: 1 },
  { q: "He runs ___ than me.", options: ["fast", "faster", "fastest", "more fast"], answer: 1 },
  { q: "I ___ a letter when you called.", options: ["write", "writes", "was writing", "wrote"], answer: 2 },
  { q: "She ___ to London next month.", options: ["go", "goes", "is going", "went"], answer: 2 },
  { q: "The cat ___ on the chair.", options: ["sit", "sits", "sitting", "sat"], answer: 1 },
  { q: "We ___ dinner at 7 PM.", options: ["have", "has", "is having", "had"], answer: 0 },
  { q: "He ___ three hours yesterday.", options: ["study", "studies", "studied", "studying"], answer: 2 },
  { q: "___ egg is on the table.", options: ["A", "An", "The", "-"], answer: 1 },
  { q: "She ___ a red dress today.", options: ["wear", "wears", "wearing", "wore"], answer: 2 },
  { q: "I never ___ chocolate.", options: ["eat", "eats", "eating", "ate"], answer: 0 },
  { q: "They ___ in the park yesterday.", options: ["walk", "walks", "walked", "walking"], answer: 2 },
  { q: "The flowers ___ in spring.", options: ["bloom", "blooms", "blooming", "bloomed"], answer: 1 },
  { q: "He ___ his keys yesterday.", options: ["lose", "loses", "lost", "losing"], answer: 2 },
  { q: "I ___ my homework already.", options: ["do", "does", "did", "doing"], answer: 2 },
  { q: "She ___ very tall.", options: ["is", "are", "am", "be"], answer: 0 },
  { q: "The movie ___ two hours.", options: ["last", "lasts", "lasted", "lasting"], answer: 1 },
  { q: "We ___ to the beach next week.", options: ["go", "goes", "going", "went"], answer: 0 },
];

// Level 3: Intermediate (B1) - 25 questions
export const LEVEL_3_QUESTIONS: QuizQ[] = [
  { q: "I ___ never been to Japan.", options: ["has", "have", "had", "having"], answer: 1 },
  { q: "If it ___, we will stay home.", options: ["rains", "rained", "rain", "raining"], answer: 0 },
  { q: "The book ___ by many students.", options: ["read", "reads", "is read", "reading"], answer: 2 },
  { q: "She asked where I ___.", options: ["live", "lived", "living", "lives"], answer: 1 },
  { q: "I'm interested ___ music.", options: ["on", "at", "in", "for"], answer: 2 },
  { q: "He enjoys ___ swimming.", options: ["go", "to go", "going", "gone"], answer: 2 },
  { q: "Neither John ___ Mary came.", options: ["or", "nor", "and", "but"], answer: 1 },
  { q: "This is ___ best day ever.", options: ["a", "an", "the", "-"], answer: 2 },
  { q: "She ___ here for 5 years.", options: ["lives", "has lived", "is living", "lived"], answer: 1 },
  { q: "By next month, they ___ the project.", options: ["finish", "will finish", "have finished", "finished"], answer: 1 },
  { q: "I would ___ if I were you.", options: ["go", "have gone", "have go", "to go"], answer: 0 },
  { q: "She ___ a car before.", options: ["has driven", "have driven", "drove", "drives"], answer: 0 },
  { q: "Unless you study, you ___.", options: ["pass", "will pass", "won't pass", "don't pass"], answer: 2 },
  { q: "I ___ working here since 2020.", options: ["am", "have been", "was", "had been"], answer: 1 },
  { q: "The problem ___ carefully.", options: ["is discussed", "discussed", "discusses", "discussing"], answer: 0 },
  { q: "If I ___ time, I will help.", options: ["have", "had", "has", "having"], answer: 0 },
  { q: "She ___ a reply yet.", options: ["didn't receive", "hasn't received", "haven't received", "doesn't receive"], answer: 1 },
  { q: "He is taller ___ his brother.", options: ["that", "than", "then", "as"], answer: 1 },
  { q: "I look forward ___ you.", options: ["to see", "seeing", "to seeing", "see"], answer: 2 },
  { q: "The cake ___ by my mom.", options: ["bake", "baked", "was baked", "is baking"], answer: 2 },
  { q: "Would you mind ___ me?", options: ["help", "helping", "to help", "helped"], answer: 1 },
  { q: "I ___ that movie before.", options: ["see", "have seen", "saw", "had seen"], answer: 1 },
  { q: "The weather ___ worse today.", options: ["become", "becomes", "became", "has become"], answer: 3 },
  { q: "Despite ___, she was happy.", options: ["the rain", "raining", "rain", "to rain"], answer: 0 },
  { q: "He ___ to Paris last year.", options: ["been", "has been", "was", "went"], answer: 3 },
];

// Level 4: Upper-Intermediate (B2) - 25 questions
export const LEVEL_4_QUESTIONS: QuizQ[] = [
  { q: "By next year, I ___ here for 10 years.", options: ["will live", "will have lived", "lived", "live"], answer: 1 },
  { q: "Had I known, I ___ him.", options: ["would tell", "would have told", "told", "will tell"], answer: 1 },
  { q: "The project ___ by the team last month.", options: ["was completed", "completed", "had completed", "completing"], answer: 0 },
  { q: "She ___ working here since 2020.", options: ["is", "has been", "was", "have been"], answer: 1 },
  { q: "I would appreciate ___ your help.", options: ["you", "your", "you to give", "if you gave"], answer: 1 },
  { q: "Unless you ___, you won't succeed.", options: ["tried", "try", "trying", "will try"], answer: 1 },
  { q: "The more you practice, ___ you become.", options: ["the best", "the better", "better", "more better"], answer: 1 },
  { q: "___ his experience, he was rejected.", options: ["Despite of", "Despite", "Although he has", "Though"], answer: 1 },
  { q: "She ___ studying medicine for years.", options: ["has been", "is", "was", "had been"], answer: 0 },
  { q: "The conference, ___ was held yesterday, was productive.", options: ["that", "which", "who", "whom"], answer: 1 },
  { q: "I ___ my opinion unless the facts change.", options: ["won't change", "haven't changed", "don't change", "am not changing"], answer: 0 },
  { q: "She would have succeeded ___ she had worked harder.", options: ["if", "unless", "provided that", "as long as"], answer: 0 },
  { q: "The report ___ to management yesterday.", options: ["was submitted", "submitted", "had submitted", "submitting"], answer: 0 },
  { q: "He ___ never admit his mistake.", options: ["would", "had", "could", "should"], answer: 0 },
  { q: "Were I in your position, I ___ do that.", options: ["wouldn't", "didn't", "haven't", "won't"], answer: 0 },
  { q: "The reason ___ he left is still unknown.", options: ["that", "why", "which", "whom"], answer: 1 },
  { q: "Only after she left ___ the truth.", options: ["did he realize", "he realized", "he had realized", "realized he"], answer: 0 },
  { q: "Neither the director ___ the actors were happy.", options: ["nor", "or", "and", "but"], answer: 0 },
  { q: "I insist that he ___ his promise.", options: ["keeps", "keep", "kept", "keeping"], answer: 1 },
  { q: "The film, ___ I saw last night, was excellent.", options: ["that", "which", "who", "what"], answer: 1 },
  { q: "She suggested ___ immediately.", options: ["that I leave", "me to leave", "I leave", "leaving"], answer: 0 },
  { q: "If it ___ yesterday, we would have stayed home.", options: ["had rained", "rained", "rains", "would rain"], answer: 0 },
  { q: "This is the best solution ___ we can find.", options: ["that", "which", "what", "who"], answer: 0 },
  { q: "I'm accustomed ___ early in the morning.", options: ["to wake", "to waking", "waking", "wake"], answer: 1 },
  { q: "The ___ of his success was hard work.", options: ["reason", "secret", "cause", "key"], answer: 3 },
];

// Level 5: Advanced (C1) - 25 questions
export const LEVEL_5_QUESTIONS: QuizQ[] = [
  { q: "Had the government intervened earlier, the crisis ___ been averted.", options: ["would have", "could have", "may have", "shall have"], answer: 0 },
  { q: "___ the magnitude of the problem, immediate action is imperative.", options: ["Given", "Giving", "To give", "Having given"], answer: 0 },
  { q: "She not only speaks French but ___ Italian and Spanish.", options: ["also speaks", "speaks also", "is speaking", "had spoke"], answer: 0 },
  { q: "The committee has recommended ___ the proposal be shelved.", options: ["that", "what", "which", "whom"], answer: 0 },
  { q: "Notwithstanding the setbacks, the project ___ forward.", options: ["proceeded", "has proceeded", "proceeds", "is proceeding"], answer: 2 },
  { q: "The mechanism ___ which this phenomenon occurs remains enigmatic.", options: ["by", "in", "at", "through"], answer: 0 },
  { q: "The disparities ___ exist between regions warrant urgent attention.", options: ["that", "which", "those which", "those that"], answer: 1 },
  { q: "His predilection for obscure terminology ___ him from attaining clarity.", options: ["deters", "deterred", "deterring", "detract"], answer: 0 },
  { q: "The paradigm shift precipitated by technological advancement has fundamentally ___ our understanding.", options: ["reconceptualized", "reconceive", "reconceived", "reconceiving"], answer: 0 },
  { q: "The treaty, to ___ both nations are signatories, stipulates unprecedented cooperation.", options: ["which", "that", "what", "whom"], answer: 0 },
  { q: "The ___ of evidence suggests culpability.", options: ["preponderance", "preponderate", "preponderating", "preponderant"], answer: 0 },
  { q: "Her propensity for verbosity often ___ clarity.", options: ["obfuscate", "obfuscates", "obfuscated", "obfuscating"], answer: 1 },
  { q: "The philosophical implications ___ remain largely unexamined.", options: ["thereof", "therein", "thereunto", "thereabout"], answer: 0 },
  { q: "Such ___ reasoning is fundamentally flawed.", options: ["specious", "speculative", "specific", "special"], answer: 0 },
  { q: "The witness corroborated the defendant's ___ account.", options: ["erstwhile", "erstwhile", "erstwhile", "erstwhile"], answer: 0 },
  { q: "Despite his ___ credentials, the proposal lacked merit.", options: ["impeccable", "impeccably", "impeccableness", "impeccably"], answer: 0 },
  { q: "The economic downturn was ___ by poor fiscal policy.", options: ["precipitated", "precipitate", "precipitating", "precipitous"], answer: 0 },
  { q: "___ the stipulations of the contract, payment is due immediately.", options: ["Pursuant to", "Pertaining to", "Perchance to", "Perdition to"], answer: 0 },
  { q: "His argument was ___ with logical fallacies.", options: ["rife", "rife", "rifely", "rifeness"], answer: 0 },
  { q: "The ___ interpretation of the statute led to judicial confusion.", options: ["ambiguous", "ambiguity", "ambiguously", "ambiguousness"], answer: 0 },
  { q: "Her ___ for academic excellence was renowned.", options: ["perspicacity", "perspicacious", "perspicaciously", "perspicacity"], answer: 0 },
  { q: "The ___ nature of quantum mechanics defied intuition.", options: ["inscrutable", "inscrutably", "inscrutability", "inscrutable"], answer: 0 },
  { q: "The evidence was ___ and indisputable.", options: ["irrefutable", "irrefutably", "irrefutability", "irrefutable"], answer: 0 },
  { q: "His ___ observations demonstrated keen intellect.", options: ["perspicacious", "perspicacity", "perspicaciously", "perspicacity"], answer: 0 },
  { q: "The ramifications of this decision are ___ and far-reaching.", options: ["momentous", "momentously", "momentousness", "momentously"], answer: 0 },
];

// Generate a pool of quizzes per topic (expanded to 15+ each for variety)
function makeQuizPool(topic: string): QuizQ[] {
  const base: Record<string, QuizQ[]> = {
    "Present Simple": [
      { q: "She ___ to school every day.", options: ["go", "goes", "going", "gone"], answer: 1 },
      { q: "They ___ football on Sundays.", options: ["plays", "playing", "play", "played"], answer: 2 },
      { q: "Water ___ at 100°C.", options: ["boil", "boils", "boiling", "boiled"], answer: 1 },
      { q: "I ___ coffee in the morning.", options: ["drink", "drinks", "drinking", "drank"], answer: 0 },
      { q: "He ___ in Ulaanbaatar.", options: ["live", "lives", "living", "lived"], answer: 1 },
      { q: "We ___ English twice a week.", options: ["studies", "study", "studying", "studied"], answer: 1 },
      { q: "The sun ___ in the east.", options: ["rise", "rises", "rising", "risen"], answer: 1 },
      { q: "She ___ three languages.", options: ["speak", "speaks", "speaking", "spoke"], answer: 1 },
      { q: "My dog ___ very friendly.", options: ["is", "are", "am", "be"], answer: 0 },
      { q: "The birds ___ in the morning.", options: ["sing", "sings", "singing", "sang"], answer: 0 },
      { q: "He ___ his car on weekends.", options: ["wash", "washes", "washing", "washed"], answer: 1 },
      { q: "I ___ the news every morning.", options: ["read", "reads", "reading", "reads"], answer: 0 },
      { q: "They ___ at 9 AM.", options: ["start", "starts", "starting", "started"], answer: 0 },
      { q: "She ___ flowers every week.", options: ["water", "waters", "watering", "watered"], answer: 1 },
      { q: "We ___ pizza twice a month.", options: ["eat", "eats", "eating", "ate"], answer: 0 },
    ],
    "Present Continuous": [
      { q: "Listen! The baby ___.", options: ["cries", "is crying", "cry", "cried"], answer: 1 },
      { q: "I ___ my homework right now.", options: ["do", "did", "am doing", "does"], answer: 2 },
      { q: "They ___ TV at the moment.", options: ["watch", "are watching", "watches", "watched"], answer: 1 },
      { q: "Why ___ you ___?", options: ["are/laughing", "do/laugh", "is/laughing", "did/laugh"], answer: 0 },
      { q: "She ___ a new book this week.", options: ["reads", "is reading", "read", "reading"], answer: 1 },
      { q: "We ___ for the bus now.", options: ["wait", "waits", "are waiting", "waited"], answer: 2 },
      { q: "The children ___ in the park.", options: ["play", "are playing", "plays", "played"], answer: 1 },
      { q: "He ___ his lunch at this moment.", options: ["eats", "is eating", "eat", "eaten"], answer: 1 },
      { q: "I ___ to music right now.", options: ["listen", "am listening", "listens", "listened"], answer: 1 },
      { q: "They ___ a house at the moment.", options: ["build", "are building", "builds", "built"], answer: 1 },
      { q: "She ___ a new dress.", options: ["wear", "is wearing", "wears", "wore"], answer: 1 },
      { q: "We ___ dinner together now.", options: ["cook", "are cooking", "cooks", "cooked"], answer: 1 },
      { q: "He ___ on the phone currently.", options: ["talks", "is talking", "talk", "talked"], answer: 1 },
      { q: "The students ___ their exam.", options: ["take", "are taking", "takes", "took"], answer: 1 },
      { q: "I ___ a delicious meal right now.", options: ["make", "am making", "makes", "made"], answer: 1 },
    ],
    "Present Perfect": [
      { q: "I ___ never been to Japan.", options: ["has", "have", "had", "having"], answer: 1 },
      { q: "She ___ her homework already.", options: ["finish", "finishes", "has finished", "finishing"], answer: 2 },
      { q: "They ___ here for three years.", options: ["live", "lives", "have lived", "lived"], answer: 2 },
      { q: "He ___ the report.", options: ["has completed", "have completed", "completed", "is completing"], answer: 0 },
      { q: "We ___ many mistakes in this test.", options: ["made", "have made", "makes", "is making"], answer: 1 },
      { q: "You ___ me this before.", options: ["told", "have told", "tells", "are telling"], answer: 1 },
      { q: "She ___ that movie three times.", options: ["has seen", "have seen", "sees", "saw"], answer: 0 },
      { q: "It ___ two hours since they arrived.", options: ["was", "has been", "have been", "is"], answer: 1 },
      { q: "I ___ my keys.", options: ["have lost", "lost", "has lost", "lose"], answer: 0 },
      { q: "They ___ to Paris.", options: ["have gone", "went", "have been", "been"], answer: 0 },
      { q: "She ___ her breakfast.", options: ["has eaten", "ate", "have eaten", "eating"], answer: 0 },
      { q: "We ___ the film before.", options: ["have watched", "watched", "watch", "are watching"], answer: 0 },
      { q: "He ___ the door.", options: ["has opened", "opened", "have opened", "opening"], answer: 0 },
      { q: "I ___ many countries.", options: ["have visited", "visited", "visit", "am visiting"], answer: 0 },
      { q: "They ___ a new car.", options: ["have bought", "bought", "buy", "are buying"], answer: 0 },
    ],
    "Past Simple": [
      { q: "She ___ to the market yesterday.", options: ["go", "goes", "went", "going"], answer: 2 },
      { q: "He ___ tennis last week.", options: ["play", "plays", "played", "playing"], answer: 2 },
      { q: "I ___ to school yesterday.", options: ["go", "goes", "went", "going"], answer: 2 },
      { q: "They ___ a movie last night.", options: ["watch", "watches", "watched", "watching"], answer: 2 },
      { q: "She ___ three cups of coffee.", options: ["drink", "drinks", "drank", "drinking"], answer: 2 },
      { q: "He ___ very tired yesterday.", options: ["is", "was", "were", "been"], answer: 1 },
      { q: "We ___ to Paris last summer.", options: ["go", "goes", "went", "going"], answer: 2 },
      { q: "The concert ___ three hours.", options: ["last", "lasts", "lasted", "lasting"], answer: 2 },
      { q: "I ___ my homework yesterday.", options: ["finish", "finishes", "finished", "finishing"], answer: 2 },
      { q: "She ___ at home all day.", options: ["stay", "stays", "stayed", "staying"], answer: 2 },
      { q: "They ___ to the beach.", options: ["go", "goes", "went", "going"], answer: 2 },
      { q: "He ___ a letter.", options: ["write", "writes", "wrote", "writing"], answer: 2 },
      { q: "I ___ breakfast at 8 AM.", options: ["have", "has", "had", "having"], answer: 2 },
      { q: "She ___ her friend on the street.", options: ["meet", "meets", "met", "meeting"], answer: 2 },
      { q: "We ___ in the rain yesterday.", options: ["walk", "walks", "walked", "walking"], answer: 2 },
    ],
    "Modal Verbs": [
      { q: "You ___ smoke here.", options: ["must", "can", "should not", "must not"], answer: 3 },
      { q: "I ___ help you if you want.", options: ["can", "must", "should", "could"], answer: 0 },
      { q: "She ___ do this work.", options: ["must", "have to", "should", "all are correct"], answer: 3 },
      { q: "You ___ be on time for class.", options: ["must", "can", "may", "might"], answer: 0 },
      { q: "He ___ speak English fluently.", options: ["can", "should", "may", "must"], answer: 0 },
      { q: "___ I help you?", options: ["Can", "Should", "May", "Must"], answer: 0 },
      { q: "You ___ leave without permission.", options: ["can", "cannot", "should", "could"], answer: 1 },
      { q: "She ___ be at home now.", options: ["must", "can", "should", "may"], answer: 0 },
      { q: "We ___ attend the meeting.", options: ["should", "must", "can", "might"], answer: 0 },
      { q: "He ___ drive a car.", options: ["can", "could", "may", "must"], answer: 0 },
      { q: "I ___ go now.", options: ["have to", "must", "should", "can"], answer: 0 },
      { q: "You ___ not talk in the library.", options: ["should", "must", "can", "will"], answer: 0 },
      { q: "___ you help me?", options: ["Could", "Should", "Will", "May"], answer: 0 },
      { q: "She ___ be a doctor.", options: ["might", "may", "could", "all are correct"], answer: 3 },
      { q: "We ___ finish by 5 PM.", options: ["must", "have to", "should", "can"], answer: 0 },
    ],
    "Passive Voice": [
      { q: "The book ___ by many students.", options: ["read", "reads", "is read", "reading"], answer: 2 },
      { q: "The cake ___ by my mom.", options: ["bake", "baked", "was baked", "is baking"], answer: 2 },
      { q: "English ___ in many countries.", options: ["is spoken", "speaks", "spoke", "speak"], answer: 0 },
      { q: "The letter ___ yesterday.", options: ["was sent", "sent", "is sent", "sends"], answer: 0 },
      { q: "The project ___ by the team.", options: ["completed", "was completed", "completes", "is completing"], answer: 1 },
      { q: "This song ___ by Mozart.", options: ["was composed", "composed", "is composing", "composes"], answer: 0 },
      { q: "The room ___ every day.", options: ["is cleaned", "cleaned", "cleans", "is cleaning"], answer: 0 },
      { q: "The problem ___ carefully.", options: ["is discussed", "discussed", "discusses", "discussing"], answer: 0 },
      { q: "The building ___ in 1990.", options: ["was built", "built", "is building", "builds"], answer: 0 },
      { q: "The poem ___ by the author.", options: ["was written", "wrote", "writes", "writing"], answer: 0 },
      { q: "The food ___ by the chef.", options: ["is prepared", "prepared", "prepare", "preparing"], answer: 0 },
      { q: "The bridge ___ next year.", options: ["will be built", "will build", "is building", "builds"], answer: 0 },
      { q: "These cars ___ in Japan.", options: ["are made", "made", "make", "making"], answer: 0 },
      { q: "The award ___ to the winner.", options: ["was given", "gave", "gives", "giving"], answer: 0 },
      { q: "The film ___ by everyone.", options: ["was enjoyed", "enjoyed", "enjoys", "enjoying"], answer: 0 },
    ],
    "Conditionals": [
      { q: "If it ___, we will stay home.", options: ["rains", "rained", "rain", "raining"], answer: 0 },
      { q: "If I ___ time, I will help.", options: ["have", "had", "has", "having"], answer: 0 },
      { q: "Unless you study, you ___.", options: ["pass", "will pass", "won't pass", "don't pass"], answer: 2 },
      { q: "She would have succeeded ___ she had worked harder.", options: ["if", "unless", "provided that", "as long as"], answer: 0 },
      { q: "If I were you, I ___ do that.", options: ["wouldn't", "didn't", "haven't", "won't"], answer: 0 },
      { q: "Had I known, I ___ him.", options: ["would tell", "would have told", "told", "will tell"], answer: 1 },
      { q: "If you ___ here, call me.", options: ["come", "comes", "came", "coming"], answer: 0 },
      { q: "Should you need help, ___ me.", options: ["call", "called", "calling", "calls"], answer: 0 },
      { q: "Provided ___ you work hard, you will succeed.", options: ["that", "what", "which", "who"], answer: 0 },
      { q: "If she ___ earlier, she would have seen him.", options: ["comes", "came", "had come", "comes"], answer: 2 },
      { q: "___ it rains, we will cancel.", options: ["If", "Unless", "Although", "Because"], answer: 0 },
      { q: "I would visit if I ___ money.", options: ["have", "had", "has", "having"], answer: 1 },
      { q: "Unless you ___ now, you will be late.", options: ["leave", "leaves", "leaving", "left"], answer: 0 },
      { q: "If they ___ earlier, they would have been on time.", options: ["left", "leave", "leaving", "had left"], answer: 3 },
      { q: "She ___ help if you ask.", options: ["will", "would", "can", "might"], answer: 2 },
    ],
    "Comparatives & Superlatives": [
      { q: "He runs ___ than me.", options: ["fast", "faster", "fastest", "more fast"], answer: 1 },
      { q: "This book is ___ than that one.", options: ["interesting", "more interesting", "most interesting", "interestinger"], answer: 1 },
      { q: "She is the ___ student in class.", options: ["good", "better", "best", "gooder"], answer: 2 },
      { q: "This car is ___ expensive.", options: ["most", "more", "less", "more"], answer: 1 },
      { q: "He is ___ than his brother.", options: ["tall", "taller", "tallest", "more tall"], answer: 1 },
      { q: "This is the ___ day of my life.", options: ["best", "better", "good", "goodest"], answer: 0 },
      { q: "She is ___ than me.", options: ["smart", "smarter", "smartest", "more smart"], answer: 1 },
      { q: "He has ___ money than I do.", options: ["much", "more", "most", "many"], answer: 1 },
      { q: "This is the ___ movie I've seen.", options: ["exciting", "more exciting", "most exciting", "excitinger"], answer: 2 },
      { q: "The weather today is ___ yesterday.", options: ["better than", "better", "best than", "good than"], answer: 0 },
      { q: "She is the ___ person I know.", options: ["kind", "kinder", "kindest", "more kind"], answer: 2 },
      { q: "This problem is ___ than I thought.", options: ["hard", "harder", "hardest", "more hard"], answer: 1 },
      { q: "He is ___ than his friend.", options: ["strong", "stronger", "strongest", "more strong"], answer: 1 },
      { q: "This is the ___ solution.", options: ["simple", "simpler", "simplest", "more simple"], answer: 2 },
      { q: "She has ___ friends than him.", options: ["many", "more", "most", "much"], answer: 1 },
    ],
    "Prepositions": [
      { q: "I'm interested ___ music.", options: ["on", "at", "in", "for"], answer: 2 },
      { q: "She is good ___ math.", options: ["in", "on", "at", "for"], answer: 2 },
      { q: "He is worried ___ the exam.", options: ["about", "of", "for", "at"], answer: 0 },
      { q: "They are excited ___ the trip.", options: ["about", "of", "for", "at"], answer: 0 },
      { q: "I am proud ___ my work.", options: ["of", "on", "for", "at"], answer: 0 },
      { q: "She relies ___ her parents.", options: ["on", "of", "for", "at"], answer: 0 },
      { q: "He is angry ___ me.", options: ["at", "on", "for", "of"], answer: 0 },
      { q: "I am grateful ___ your help.", options: ["for", "of", "on", "at"], answer: 0 },
      { q: "She is afraid ___ spiders.", options: ["of", "on", "for", "at"], answer: 0 },
      { q: "He complained ___ the noise.", options: ["about", "of", "for", "at"], answer: 0 },
      { q: "I'm looking forward ___ you.", options: ["to", "for", "at", "of"], answer: 0 },
      { q: "She insists ___ her opinion.", options: ["on", "of", "for", "at"], answer: 0 },
      { q: "He apologized ___ his mistake.", options: ["for", "of", "on", "at"], answer: 0 },
      { q: "I am responsible ___ the project.", options: ["for", "of", "on", "at"], answer: 0 },
      { q: "She is aware ___ the problem.", options: ["of", "on", "for", "at"], answer: 0 },
    ],
    "Gerunds & Infinitives": [
      { q: "He enjoys ___ swimming.", options: ["go", "to go", "going", "gone"], answer: 2 },
      { q: "She wants ___ to Paris.", options: ["go", "to go", "going", "gone"], answer: 1 },
      { q: "Would you mind ___ me?", options: ["help", "helping", "to help", "helped"], answer: 1 },
      { q: "I avoid ___ late.", options: ["go", "to go", "going", "gone"], answer: 2 },
      { q: "He decides ___ early.", options: ["leave", "to leave", "leaving", "left"], answer: 1 },
      { q: "She suggests ___ the park.", options: ["visit", "to visit", "visiting", "visited"], answer: 2 },
      { q: "I promise ___ on time.", options: ["be", "to be", "being", "been"], answer: 1 },
      { q: "They risk ___ the game.", options: ["lose", "to lose", "losing", "lost"], answer: 2 },
      { q: "He starts ___ hard.", options: ["work", "to work", "working", "worked"], answer: 2 },
      { q: "I finish ___ my homework.", options: ["do", "to do", "doing", "done"], answer: 2 },
      { q: "She practices ___ the piano.", options: ["play", "to play", "playing", "played"], answer: 2 },
      { q: "He dares ___ jump.", options: ["to", "to jump", "jump", "jumping"], answer: 1 },
      { q: "I hope ___ you soon.", options: ["see", "to see", "seeing", "seen"], answer: 1 },
      { q: "They stop ___ rest.", options: ["to", "to rest", "rest", "resting"], answer: 1 },
      { q: "She continues ___ studying.", options: ["to", "to study", "study", "studying"], answer: 3 },
    ],
  };
  if (base[topic]) return base[topic];
  // Generic fallback pool customized with topic name
  return [
    { q: `Choose the correct use of ${topic}: "She ___ very well."`, options: ["sing", "sings", "singing", "sang"], answer: 1 },
    { q: `Identify correct sentence (${topic}).`, options: ["He don't know.", "He doesn't knows.", "He doesn't know.", "He not know."], answer: 2 },
    { q: `${topic}: "I have ___ apple."`, options: ["a", "an", "the", "-"], answer: 1 },
    { q: `${topic}: pick the right modal: "You ___ smoke here."`, options: ["should", "must not", "can", "would"], answer: 1 },
    { q: `${topic}: comparative of "good".`, options: ["gooder", "more good", "better", "best"], answer: 2 },
    { q: `${topic}: "If I ___ rich, I would travel."`, options: ["am", "was", "were", "be"], answer: 2 },
    { q: `${topic}: passive of "They built it."`, options: ["It built.", "It was built.", "It is build.", "It built was."], answer: 1 },
    { q: `${topic}: preposition: "I'm good ___ math."`, options: ["in", "on", "at", "for"], answer: 2 },
    { q: `${topic}: "He ___ to the store yesterday."`, options: ["go", "goes", "went", "going"], answer: 2 },
    { q: `${topic}: "She ___ completed her work."`, options: ["have", "has", "had", "having"], answer: 1 },
  ];
}

export const GRAMMAR_QUIZZES: Record<string, QuizQ[]> = Object.fromEntries(
  GRAMMAR_TOPICS.map((t) => [t, makeQuizPool(t)]),
);

export const READING_PASSAGES = [
  {
    title: "Naadam Festival",
    text: "Naadam is Mongolia's largest summer festival. It features three traditional sports: wrestling, horse racing, and archery. People wear colorful deels and gather in Ulaanbaatar.",
    questions: [
      { q: "How many sports does Naadam feature?", options: ["2", "3", "4", "5"], answer: 1 },
      { q: "When is Naadam held?", options: ["Winter", "Spring", "Summer", "Autumn"], answer: 2 },
      { q: "What do people wear?", options: ["Jeans", "Deels", "Suits", "Uniforms"], answer: 1 },
      { q: "Where do people gather for Naadam?", options: ["Ulaanbaatar", "London", "Tokyo", "Sydney"], answer: 0 },
      { q: "Which sport is part of Naadam?", options: ["Swimming", "Archery", "Basketball", "Tennis"], answer: 1 },
    ],
    level: 1,
  },
  {
    title: "The Gobi Desert",
    text: "The Gobi is one of the largest deserts in the world. It is cold in winter and hot in summer. Camels and snow leopards live there.",
    questions: [
      { q: "What animals live in the Gobi?", options: ["Lions and tigers", "Camels and leopards", "Bears", "Wolves only"], answer: 1 },
      { q: "Gobi is one of the ___ deserts.", options: ["smallest", "largest", "wettest", "coldest only"], answer: 1 },
      { q: "How is Gobi in summer?", options: ["Cold", "Hot", "Snowy", "Rainy"], answer: 1 },
      { q: "How is the Gobi in winter?", options: ["Cold", "Tropical", "Rainy", "Humid"], answer: 0 },
      { q: "What type of place is the Gobi?", options: ["A forest", "A desert", "A city", "An ocean"], answer: 1 },
    ],
    level: 1,
  },
  {
    title: "Modern Ulaanbaatar",
    text: "Ulaanbaatar is the capital of Mongolia. It is home to over 1.5 million people. The city blends modern skyscrapers with traditional ger districts.",
    questions: [
      { q: "What is Ulaanbaatar?", options: ["A river", "The capital", "A mountain", "A desert"], answer: 1 },
      { q: "Population is over...", options: ["500,000", "1 million", "1.5 million", "5 million"], answer: 2 },
      { q: "City blends modern with...", options: ["jungles", "ger districts", "beaches", "farms"], answer: 1 },
      { q: "What modern buildings are mentioned?", options: ["Skyscrapers", "Castles", "Igloos", "Temples only"], answer: 0 },
      { q: "Ulaanbaatar is home to over ___ people.", options: ["1.5 million", "10,000", "100,000", "20 million"], answer: 0 },
    ],
    level: 1,
  },

  // LEVEL 2 - Elementary (A2) - Simple past, basic present perfect
  {
    title: "My First Day at School",
    text: "I went to school for the first time. My teacher was very nice. She showed me the classroom and introduced me to the other students. I made two new friends, and we played together at lunch time. It was a great day.",
    questions: [
      { q: "Who was nice on the first day?", options: ["The principal", "The teacher", "The students", "The cook"], answer: 1 },
      { q: "What did the teacher do?", options: ["Gave a test", "Showed the classroom", "Left early", "Stayed home"], answer: 1 },
      { q: "How many friends did the writer make?", options: ["One", "Two", "Three", "Four"], answer: 1 },
      { q: "When did they play together?", options: ["At breakfast", "In class", "At lunch", "After school"], answer: 2 },
      { q: "How was the day?", options: ["Bad", "Boring", "Great", "Scary"], answer: 2 },
    ],
    level: 2,
  },
  {
    title: "A Day in the Market",
    text: "Yesterday, I went to the market with my mother. We bought fresh vegetables, fruits, and fish. The market was very busy. Many people were selling different things. My mother talked to the seller and got a good price. I carried the bags home, and we made a delicious dinner.",
    questions: [
      { q: "Who did the writer go to the market with?", options: ["Father", "Mother", "Sister", "Friends"], answer: 1 },
      { q: "What did they buy at the market?", options: ["Only vegetables", "Only fruits", "Vegetables, fruits, and fish", "Just bread"], answer: 2 },
      { q: "How was the market?", options: ["Quiet", "Closed", "Very busy", "Small"], answer: 2 },
      { q: "What did they make at home?", options: ["Breakfast", "Lunch", "Dinner", "Snacks"], answer: 2 },
      { q: "What did the mother do with the seller?", options: ["Argued", "Talked and got a good price", "Complained", "Left without buying"], answer: 1 },
    ],
    level: 2,
  },
  {
    title: "Learning to Ride a Bike",
    text: "Last summer, I learned to ride a bike. At first, I was afraid of falling. My father helped me. He held the back of the bike while I learned to balance. After many tries, I fell down several times but didn't give up. Finally, I could ride by myself. I was very proud and happy.",
    questions: [
      { q: "What was the writer afraid of?", options: ["The bike", "Falling", "The father", "The summer"], answer: 1 },
      { q: "Who helped the writer learn?", options: ["Mother", "Sister", "Father", "Friend"], answer: 2 },
      { q: "How many times did the writer fall?", options: ["Once", "Twice", "Several times", "Never"], answer: 2 },
      { q: "Did the writer give up?", options: ["Yes", "No", "Maybe", "Eventually"], answer: 1 },
      { q: "What did the writer learn to do?", options: ["Run", "Ride a bike", "Swim", "Cook"], answer: 1 },
    ],
    level: 2,
  },

  // LEVEL 3 - Intermediate (B1) - Present perfect, more complex ideas
  {
    title: "The Effects of Technology on Communication",
    text: "Technology has changed how we communicate. In the past, people sent letters which took weeks to arrive. Today, we can send messages instantly through email or chat applications. However, face-to-face communication has become less common. While technology connects us across distances, it has also reduced personal interactions. Many people now prefer to text rather than call. This shift has both advantages and disadvantages for our society.",
    questions: [
      { q: "How has technology changed communication?", options: ["Made it slower", "Made it instant", "Made it impossible", "Made it more personal"], answer: 1 },
      { q: "What did people do in the past to communicate?", options: ["Sent emails", "Called often", "Sent letters", "Used chat apps"], answer: 2 },
      { q: "What has technology reduced?", options: ["Letter writing", "Personal interactions", "Texting", "Distance"], answer: 1 },
      { q: "What do many people now prefer?", options: ["Calling", "Visiting", "Texting", "Writing letters"], answer: 2 },
      { q: "Does the passage say technology has only advantages?", options: ["Yes", "No", "Maybe", "Unclear"], answer: 1 },
    ],
    level: 3,
  },
  {
    title: "Cultural Exchange Programs",
    text: "Cultural exchange programs have become increasingly popular among students. These programs allow young people to live in foreign countries, attend schools, and experience different cultures firsthand. Participants often develop greater understanding and appreciation for other ways of life. They learn new languages, make international friendships, and gain valuable life skills. By participating in such programs, students become more independent and culturally aware. Many educators believe these experiences are essential for developing global citizens.",
    questions: [
      { q: "What do cultural exchange programs allow students to do?", options: ["Stay home", "Learn only languages", "Experience different cultures", "Avoid school"], answer: 2 },
      { q: "What do participants often develop?", options: ["Fear", "Greater understanding", "Confusion", "Homesickness only"], answer: 1 },
      { q: "What skills do students gain?", options: ["Only academic", "Valuable life skills", "Only sports", "No skills"], answer: 1 },
      { q: "What do educators believe these experiences help develop?", options: ["Athletes", "Global citizens", "Workers", "Teachers only"], answer: 1 },
      { q: "What is NOT mentioned as a benefit?", options: ["New languages", "Friendships", "Life skills", "Athletic abilities"], answer: 3 },
    ],
    level: 3,
  },
  {
    title: "Environmental Conservation Efforts",
    text: "Governments and organizations worldwide have implemented various environmental conservation strategies. These efforts include protecting endangered species, establishing national parks, and reducing carbon emissions. Although progress has been made, scientists warn that more aggressive action is needed to prevent irreversible damage. Individuals can contribute by adopting sustainable practices, supporting renewable energy, and reducing waste. The success of environmental conservation depends on collective responsibility and commitment from both governments and citizens.",
    questions: [
      { q: "What do conservation efforts include?", options: ["Only making money", "Protecting species and establishing parks", "Only tourism", "Nothing important"], answer: 1 },
      { q: "What warning have scientists issued?", options: ["Conservation is working", "More action is needed", "Nothing needs to change", "All problems are solved"], answer: 1 },
      { q: "How can individuals contribute?", options: ["They cannot", "By sustainable practices and reducing waste", "Only by voting", "By doing nothing"], answer: 1 },
      { q: "According to the passage, what determines success?", options: ["Only government action", "Only individual action", "Collective responsibility", "Money only"], answer: 2 },
      { q: "What is the main theme of the passage?", options: ["Governments always help", "Individuals can't help", "Everyone must work together", "Nothing matters"], answer: 2 },
    ],
    level: 3,
  },

  // LEVEL 4 - Upper-Intermediate (B2) - Complex sentences, inference
  {
    title: "The Evolution of E-Learning",
    text: "The rapid advancement of digital technology has revolutionized the educational landscape. E-learning platforms have evolved from simple text-based modules to sophisticated, interactive systems that incorporate multimedia, artificial intelligence, and personalized learning pathways. Initially met with skepticism, online education has demonstrated remarkable efficacy, particularly when combined with traditional instruction in hybrid models. However, critics argue that digital learning environments may perpetuate inequalities, as not all students have equitable access to reliable internet connectivity and devices. Consequently, institutions must address these accessibility concerns while leveraging technological innovations to create inclusive educational ecosystems.",
    questions: [
      { q: "How have e-learning platforms evolved?", options: ["They've remained basic", "From simple to sophisticated systems", "They've disappeared", "They've become simpler"], answer: 1 },
      { q: "What was the initial reception to online education?", options: ["Universal praise", "Widespread skepticism", "Complete acceptance", "No reaction"], answer: 1 },
      { q: "What does the passage imply about hybrid models?", options: ["They're ineffective", "They combine online and traditional methods", "They only use technology", "They're outdated"], answer: 1 },
      { q: "What concern do critics raise?", options: ["Technology is too advanced", "Digital learning may increase inequalities", "Internet is always available", "Everyone has devices"], answer: 1 },
      { q: "What must institutions do?", options: ["Ignore accessibility", "Address concerns and create inclusive systems", "Eliminate technology", "Only use traditional methods"], answer: 1 },
    ],
    level: 4,
  },
  {
    title: "The Impact of Globalization on Indigenous Cultures",
    text: "Globalization has precipitated profound transformations in indigenous communities worldwide. While increased connectivity and economic opportunities have facilitated development, these same forces have simultaneously threatened cultural autonomy and traditional knowledge systems. The homogenizing effects of global markets have undermined indigenous languages and practices, as younger generations increasingly adopt dominant cultural norms. Paradoxically, digital technologies have also enabled indigenous communities to preserve and promote their heritage through digital archives and cultural platforms. The challenge lies in maintaining cultural integrity while selectively embracing beneficial aspects of global integration, a delicate equilibrium that requires sustained policy interventions and community agency.",
    questions: [
      { q: "What is the author's main argument about globalization?", options: ["It's entirely beneficial", "It has both positive and negative effects", "It's completely harmful", "It's irrelevant"], answer: 1 },
      { q: "What threat does globalization pose?", options: ["Economic growth", "Cultural autonomy and traditions", "Connectivity", "Development"], answer: 1 },
      { q: "What paradox does the passage present?", options: ["There is no paradox", "Technology threatens and preserves culture", "Culture is unchanging", "Globalization only helps"], answer: 1 },
      { q: "What does the passage suggest is needed?", options: ["Complete isolation", "Unrestricted globalization", "Selective integration with policy support", "Rejecting all technology"], answer: 2 },
      { q: "What enables indigenous communities to preserve heritage?", options: ["Isolation only", "Complete rejection of technology", "Digital technologies and platforms", "Traditional methods only"], answer: 2 },
    ],
    level: 4,
  },
  {
    title: "Renewable Energy and Economic Transformation",
    text: "The transition to renewable energy sources represents a pivotal moment in global economic restructuring. While proponents assert that clean energy infrastructure generates sustainable employment and mitigates climate change, skeptics contend that the transition period poses significant economic disruption for fossil fuel-dependent regions. Technological innovations in solar and wind power have substantially reduced production costs, rendering renewable energy increasingly competitive. Nevertheless, infrastructure investments remain formidable, and policy frameworks must reconcile environmental imperatives with economic viability. Countries that proactively invest in renewable infrastructure demonstrate enhanced long-term resilience, though the distribution of transition benefits remains inequitable across different demographics and geographical regions.",
    questions: [
      { q: "What do proponents claim about clean energy?", options: ["It's ineffective", "It generates jobs and mitigates climate change", "It's too expensive", "It's unreliable"], answer: 1 },
      { q: "What concern do skeptics raise?", options: ["Climate change doesn't exist", "Economic disruption in fossil fuel regions", "Renewables are too cheap", "Transition is unnecessary"], answer: 1 },
      { q: "What has happened to renewable energy costs?", options: ["They've increased", "They've remained stable", "They've substantially decreased", "They're unpredictable"], answer: 2 },
      { q: "What must policy frameworks do?", options: ["Ignore economics", "Reconcile environmental and economic needs", "Only focus on profit", "Reject all renewables"], answer: 1 },
      { q: "What is implied about transition benefits?", options: ["Everyone benefits equally", "Benefits are inequitably distributed", "Nobody benefits", "Only governments benefit"], answer: 1 },
    ],
    level: 4,
  },

  // LEVEL 5 - Advanced (C1) - Nuanced, sophisticated arguments
  {
    title: "The Epistemological Implications of Artificial Intelligence",
    text: "The exponential advancement of artificial intelligence systems precipitates fundamental epistemological questions regarding knowledge acquisition and validation. Machine learning algorithms, operating through pattern recognition rather than causal reasoning, challenge traditional philosophical frameworks predicated on ontological and phenomenological understanding. While these systems demonstrate remarkable proficiency in data synthesis and predictive modeling, their opacity—often characterized as the 'black box' problem—undermines epistemic transparency and accountability. Consequently, the integration of AI into domains requiring human judgment necessitates rigorous examination of algorithmic bias, inherent limitations of computational approaches, and the irreducibility of human cognition. The philosophical implications extend beyond mere technical considerations; they implicate the very foundations of knowledge production and the nature of human expertise in an increasingly algorithmic society.",
    questions: [
      { q: "What epistemological challenge do AI systems present?", options: ["None", "They redefine knowledge validation frameworks", "They simplify understanding", "They're irrelevant to philosophy"], answer: 1 },
      { q: "How do machine learning algorithms primarily operate?", options: ["Through causal reasoning", "Through pattern recognition", "Through intuition", "Through human guidance only"], answer: 1 },
      { q: "What is the 'black box' problem?", options: ["A storage device", "Algorithmic opacity and lack of transparency", "A mythical concept", "An unsolved mathematical puzzle"], answer: 1 },
      { q: "What does the passage suggest about AI limitations?", options: ["There are none", "They're merely technical", "They're philosophical and irrefutable", "They don't matter"], answer: 2 },
      { q: "What is the author's ultimate concern?", options: ["Computers work too well", "The implications for knowledge production and expertise", "AI is helpful", "Technology is simple"], answer: 1 },
    ],
    level: 5,
  },
  {
    title: "Post-Structuralist Critique of Linguistic Determinism",
    text: "Post-structuralist theorists contest the determinist assertion that language constitutes an autonomous semiotic system predetermining conceptual possibilities. Derrida's deconstructive methodology elucidates the aporias and paradoxes inherent within logocentric frameworks, demonstrating how meaning perpetually defers through chains of signification. This decentralization of authorial intention and textual stability problematizes traditional hermeneutic approaches, foregrounding the indeterminacy of interpretation. Furthermore, Foucauldian genealogies expose how discursive formations construct subjectivity and power relations, challenging humanistic conceptions of autonomous agency. The implications prove profoundly consequential: if language does not transparently represent preexisting reality but rather constitutes it through contingent historical processes, then the relationship between signifier and signified becomes fundamentally unstable, necessitating continuous reexamination of categorical assumptions undergirding academic and social institutions.",
    questions: [
      { q: "What do post-structuralists contest?", options: ["Everything", "Linguistic determinism", "Writing in general", "Language universality"], answer: 1 },
      { q: "What does Derrida's methodology demonstrate?", options: ["Language is simple", "Meaning perpetually defers through signification", "There's no meaning", "Meaning is fixed"], answer: 1 },
      { q: "What does Foucault's genealogy expose?", options: ["Historical facts only", "How discourses construct subjectivity", "Language rules", "Nothing important"], answer: 1 },
      { q: "According to the passage, what is the relationship between signifier and signified?", options: ["Transparent and stable", "Fundamentally unstable", "Fixed forever", "Nonexistent"], answer: 1 },
      { q: "What implications does the passage suggest?", options: ["None", "Categorical assumptions require continuous reexamination", "Nothing matters", "Traditional approaches are correct"], answer: 1 },
    ],
    level: 5,
  },
  {
    title: "Quantum Mechanics and Metaphysical Implications",
    text: "The Copenhagen interpretation of quantum mechanics provokes profound metaphysical perplexities regarding the nature of ontological reality. The wave-particle duality and superposition principles fundamentally challenge classical determinism and realism, suggesting that subatomic entities possess indeterminate properties until subjected to measurement. This interpretive framework implicates the observer in constituting reality itself, thereby problematizing subject-object dichotomies and the epistemological status of objective knowledge. Bell's theorem and subsequent experimental confirmations of non-local entanglement corroborate the ineluctability of quantum indeterminacy, confounding intuitions predicated on spatiotemporal locality and causal continuity. Consequently, contemporary physics necessitates reconceptualizing fundamental assumptions about causality, determinism, and the nature of being itself, precipitating ramifications extending far beyond physics into philosophy of science, epistemology, and metaphysics.",
    questions: [
      { q: "What does the Copenhagen interpretation challenge?", options: ["Nothing", "Classical determinism and realism", "Quantum theory", "All science"], answer: 1 },
      { q: "What does superposition suggest about properties?", options: ["They're always determined", "They're indeterminate until measured", "They don't exist", "They're classical"], answer: 1 },
      { q: "What does the observer problem implicate?", options: ["Nothing", "The observer constitutes reality", "Reality is objective", "Observers are irrelevant"], answer: 1 },
      { q: "What do Bell's theorem and entanglement confirm?", options: ["Locality is absolute", "Quantum indeterminacy is ineluctable", "Determinism prevails", "Experiments are useless"], answer: 1 },
      { q: "What does physics necessitate?", options: ["Maintaining classical assumptions", "Reconceptualizing fundamental assumptions", "Ignoring philosophy", "No changes"], answer: 1 },
    ],
    level: 5,
  },
];

export const VOCAB_POOL: { word: string; def: string }[] = [
  { word: "achieve", def: "to successfully reach a goal" },
  { word: "brave", def: "showing courage" },
  { word: "curious", def: "eager to learn or know" },
  { word: "diligent", def: "showing care and effort in work" },
  { word: "eager", def: "wanting very much to do something" },
  { word: "fragile", def: "easily broken" },
  { word: "generous", def: "willing to give" },
  { word: "honest", def: "truthful and sincere" },
  { word: "improve", def: "to become better" },
  { word: "journey", def: "an act of traveling" },
  { word: "knowledge", def: "information and understanding" },
  { word: "loyal", def: "faithful to a person or cause" },
  { word: "modest", def: "not boastful" },
  { word: "novel", def: "new and original" },
  { word: "opportunity", def: "a chance for progress" },
  { word: "persuade", def: "to convince someone" },
  { word: "quiet", def: "making little noise" },
  { word: "reliable", def: "able to be trusted" },
  { word: "sincere", def: "free from pretense" },
  { word: "talented", def: "having a natural skill" },
];

export const SCRAMBLE_SENTENCES: string[] = [
  "I eat rice every day",
  "She reads books in the library",
  "We play football on Sundays",
  "They watch movies at home",
  "He drinks coffee every morning",
  "My brother teaches English",
  "The cat catches the mouse",
  "Students study grammar carefully",
  "Mongolian children love horses",
  "Tourists visit Ulaanbaatar often",
];

export const BLASTER_QUESTIONS: QuizQ[] = [
  { q: "Pick correct: ___ apple a day keeps the doctor away.", options: ["A", "An", "The", "-"], answer: 1 },
  { q: "She ___ to the market yesterday.", options: ["go", "goes", "went", "gone"], answer: 2 },
  { q: "There ___ many books on the shelf.", options: ["is", "are", "was", "be"], answer: 1 },
  { q: "He runs ___ than me.", options: ["fast", "faster", "fastest", "more fast"], answer: 1 },
  { q: "I ___ never been to Japan.", options: ["has", "have", "had", "having"], answer: 1 },
  { q: "If it ___, we will stay home.", options: ["rains", "rained", "rain", "raining"], answer: 0 },
  { q: "The book ___ by many students.", options: ["read", "reads", "is read", "reading"], answer: 2 },
  { q: "She asked where I ___.", options: ["live", "lived", "living", "lives"], answer: 1 },
  { q: "I'm interested ___ music.", options: ["on", "at", "in", "for"], answer: 2 },
  { q: "He enjoys ___ swimming.", options: ["go", "to go", "going", "gone"], answer: 2 },
  { q: "Neither John ___ Mary came.", options: ["or", "nor", "and", "but"], answer: 1 },
  { q: "This is ___ best day ever.", options: ["a", "an", "the", "-"], answer: 2 },
];

export const PLACEMENT_QUESTIONS: QuizQ[] = [
  { q: "I ___ a student.", options: ["am", "is", "are", "be"], answer: 0 },
  { q: "She ___ from Mongolia.", options: ["am", "is", "are", "be"], answer: 1 },
  { q: "They ___ playing now.", options: ["is", "am", "are", "be"], answer: 2 },
  { q: "I ___ to school yesterday.", options: ["go", "goes", "went", "going"], answer: 2 },
  { q: "She ___ her homework already.", options: ["finish", "finishes", "has finished", "finishing"], answer: 2 },
  { q: "If I ___ time, I will help.", options: ["have", "had", "has", "having"], answer: 0 },
  { q: "He is taller ___ his brother.", options: ["that", "than", "then", "as"], answer: 1 },
  { q: "The cake ___ by my mom.", options: ["bake", "baked", "was baked", "is baking"], answer: 2 },
  { q: "I look forward ___ you.", options: ["to see", "seeing", "to seeing", "see"], answer: 2 },
  { q: "She said she ___ tired.", options: ["is", "was", "be", "are"], answer: 1 },
  { q: "Neither answer ___ correct.", options: ["are", "is", "be", "were"], answer: 1 },
  { q: "By next year, I ___ here for 10 years.", options: ["will live", "will have lived", "lived", "live"], answer: 1 },
];

export function shuffle<T>(arr: T[]): T[] {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export function pickRandom<T>(arr: T[], n: number): T[] {
  return shuffle(arr).slice(0, n);
}
